### ISSUE TITLE
Add README 

### ISSUE THREAD

**Issue by daguar** [codeforamerica/snap-it-up#28] opened 2015-02-27 21:43 UTC

**Comment by Mr0grog** [comment] 2015-02-27 21:52
Hey @daguar, this is a dupe of #1, which has almost exactly the same title.

**Closed as completed by Mr0grog** 2015-02-27 21:52 UTC

**Comment by Mr0grog** [comment] 2015-02-27 21:53
(no offense taken, but maaaybe do a quick scan of the issue list before posting?)

**Comment by daguar** [comment] 2015-02-27 22:02
Bah, sorry. Was flying through and was frustrated mostly that I couldn't find production. I've added it as the URL for the repo.

**Comment by Mr0grog** [comment] 2015-02-27 23:13
Cool, no worries. Should the repo URL be http://status.citizenonboard.com/ or http://snap-status.herokuapp.com? Both totally valid, though confusingly separate :P
